package com.sakethh.linkora

import androidx.compose.runtime.Composable
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.remember
import androidx.datastore.preferences.core.stringPreferencesKey
import com.sakethh.linkora.preferences.AppPreferenceType
import com.sakethh.linkora.preferences.AppPreferences
import com.sakethh.linkora.di.DependencyContainer
import com.sakethh.linkora.domain.LinkoraPlaceHolder
import com.sakethh.linkora.utils.Constants
import kotlinx.coroutines.runBlocking

typealias LocalizedStringKey = String

object Localization {
    private val localizedStrings = mutableStateMapOf<LocalizedStringKey, String>()

    fun loadLocalizedStrings(
        languageCode: String, forceLoadDefaultValues: Boolean = false
    ) = runBlocking {
        if (languageCode == Constants.DEFAULT_APP_LANGUAGE_CODE && forceLoadDefaultValues.not()) return@runBlocking
        if (AppPreferences.preferredAppLanguageCode.value != languageCode) {
            AppPreferences.preferredAppLanguageName.value =
                if (languageCode == Constants.DEFAULT_APP_LANGUAGE_CODE) {
                    Constants.DEFAULT_APP_LANGUAGE_NAME
                } else {
                    DependencyContainer.localizationRepo.getLanguageNameForTheCode(
                        languageCode
                    )
                }
            AppPreferences.preferredAppLanguageCode.value = languageCode
            DependencyContainer.preferencesRepo.changePreferenceValue(
                stringPreferencesKey(AppPreferenceType.APP_LANGUAGE_NAME.name),
                AppPreferences.preferredAppLanguageName.value
            )
            DependencyContainer.preferencesRepo.changePreferenceValue(
                stringPreferencesKey(AppPreferenceType.APP_LANGUAGE_CODE.name),
                AppPreferences.preferredAppLanguageCode.value
            )
        }
        Key.entries.forEach { key ->
            localizedStrings[key.name] =
                if (languageCode == Constants.DEFAULT_APP_LANGUAGE_CODE || forceLoadDefaultValues) {
                    key.defaultValue
                } else {
                    DependencyContainer.localizationRepo.getLocalizedStringValueFor(
                        key.name, languageCode
                    ).run {
                        if (this == null || this.isBlank()) {
                            key.defaultValue
                        } else {
                            this
                        }
                    }
                }
        }
    }

    @Composable
    fun rememberLocalizedString(key: Key): String {
        return remember {
            derivedStateOf {
                localizedStrings[key.name] ?: key.defaultValue
            }
        }.value
    }

    fun getLocalizedString(key: Key): String {
        return localizedStrings[key.name] ?: key.defaultValue
    }

    // very bad way but fine for now, will be replaced with build-time generation
    /* fun generateKeysAndDefaultValues() {
         File("/home/saketh/StudioProjects/Linkora/locales/default_en.json").writeText(
             Key.entries.joinToString(
                 separator = ",\n", prefix = "{", postfix = "}"
             ) {
                 """"${it.name}":"${it.defaultValue.replace("\n", "\\n").replace("\"", "\\\"")}""""
             })
     }*/

    enum class Key(val defaultValue: String) {
        Settings(defaultValue = "设置"),
        Theme(defaultValue = "主题"),
        General(defaultValue = "一般"),
        Advanced(defaultValue = "高级"),
        Layout(defaultValue = "布局"),
        Language(defaultValue = "语言"),
        Data(defaultValue = "数据"),
        Privacy(defaultValue = "隐私"),
        About(defaultValue = "关于"),
        Acknowledgments(defaultValue = "致谢"),
        UseDarkMode(defaultValue = "使用深色主题"),
        AppLanguage(defaultValue = "应用语言"),
        DisplayingRemoteStrings(defaultValue = "显示远程字符串"),
        ResetAppLanguage(defaultValue = "重置应用语言"),
        AvailableLanguages(defaultValue = "可用语言"),
        LoadServerStrings(defaultValue = "加载服务器字符串"),
        LoadCompiledStrings(defaultValue = "加载编译字符串"),
        UpdateLanguageStrings(defaultValue = "更新语言字符串"),
        DownloadLanguageStrings(defaultValue = "下载语言字符串"),
        RemoveLanguageStrings(defaultValue = "删除语言字符串"),
        DisplayingCompiledStrings(defaultValue = "显示编译字符串"),
        Home(defaultValue = "主页"),
        Search(defaultValue = "搜索"),
        History(defaultValue = "历史"),
        HistoryLinks(defaultValue = "历史链接"),
        FolderLinks(defaultValue = "文件夹链接"),
        Collections(defaultValue = "收藏"),
        LinkoraServerSetup(defaultValue = "Linkora 服务器设置"),
        CollectionDetailPane(defaultValue = "收藏详情面板"),
        CreateANewFolder(defaultValue = "创建新文件夹"),
        CreateANewFolderIn(defaultValue = "在 ${LinkoraPlaceHolder.First.value} 中创建新文件夹"),
        Create(defaultValue = "创建"),
        AddANewLink(defaultValue = "添加新链接"),
        SavedLinks(defaultValue = "已保存链接"),
        AddANewLinkInImportantLinks(defaultValue = "在重要链接中添加新链接"),
        AddANewLinkInSavedLinks(defaultValue = "在已保存链接中添加新链接"),
        AddANewLinkIn(defaultValue = "在 ${LinkoraPlaceHolder.First.value} 中添加新链接"),
        LinkAddress(defaultValue = "链接地址"),
        TitleForTheLink(defaultValue = "链接标题"),
        NoteForSavingTheLink(defaultValue = "保存链接的备注"),
        AutoDetectTitleIsEnabled(defaultValue = "自动检测标题当前已启用。"),
        DataRetrievalDisabled(defaultValue = "数据检索被阻止，因为“强制保存链接而不检索”功能当前已启用。"),
        ForceAutoDetectTitle(defaultValue = "强制自动检测标题"),
        RetryingWithSecondaryUserAgent(defaultValue = "使用备用用户代理重试元数据检索。"),
        ForceSaveWithoutRetrievingMetadata(defaultValue = "强制保存而不检索元数据"),
        AddIn(defaultValue = "添加到"),
        InitialRequestFailed(defaultValue = "初始请求失败。"),
        ImportantLinks(defaultValue = "重要链接"),
        Save(defaultValue = "保存"),
        SaveInThisFolder(defaultValue = "保存到此文件夹"),
        Cancel(defaultValue = "取消"),
        FolderName(defaultValue = "文件夹名称"),
        NoteForCreatingTheFolder(defaultValue = "创建文件夹的备注"),
        AllLinks(defaultValue = "所有链接"),
        Links(defaultValue = "链接"),
        Archive(defaultValue = "归档"),
        ArchiveLinks(defaultValue = "归档链接"),
        Folders(defaultValue = "文件夹"),
        SuccessfullySavedConnectionDetails(defaultValue = "成功保存连接详细信息。"),
        DeletedTheServerConnectionSuccessfully(defaultValue = "成功删除服务器连接。"),
        UseInAppBrowser(defaultValue = "使用应用内浏览器"),
        UseInAppBrowserDesc(defaultValue = "启用此选项以在应用内打开链接；否则，点击链接时将使用默认浏览器打开。"),
        EnableHomeScreen(defaultValue = "启用主屏幕"),
        EnableHomeScreenDesc(defaultValue = "如果启用，底部导航栏将显示主屏幕选项；如果未启用，主屏幕选项将不会显示。"),
        AutoDetectTitle(defaultValue = "自动检测标题"),
        AutoDetectTitleDesc(defaultValue = "注意：这可能无法检测到每个网站的标题。"),
        ForceSaveWithoutRetrievingMetadataDesc(defaultValue = "链接将按原样保存，不会获取任何数据。注意：这将影响从链接菜单刷新链接，如果启用此功能，链接将不会被刷新。"),
        ShowAssociatedImageInLinkMenu(defaultValue = "在链接菜单中显示相关图片"),
        ShowAssociatedImageInLinkMenuDesc(defaultValue = "启用以在链接菜单中显示相关图片。"),
        AutoCheckForUpdates(defaultValue = "自动检查更新"),
        AutoCheckForUpdatesDesc(defaultValue = "启用以在应用启动时自动检查更新。禁用则需手动检查。"),
        ShowDescriptionForSettings(defaultValue = "显示设置描述"),
        ShowDescriptionForSettingsDesc(defaultValue = "启用以显示设置的详细描述。禁用则仅显示标题。"),
        ManageConnectedServer(defaultValue = "管理连接的服务器"),
        ManageConnectedServerDesc(defaultValue = "您的数据已同步到 Linkora 服务器。点击以管理或断开连接。"),
        CurrentlyConnectedTo(defaultValue = "当前连接到"),
        SyncType(defaultValue = "同步类型"),
        EditServerConfiguration(defaultValue = "编辑服务器配置"),
        DeleteTheServerConnection(defaultValue = "删除连接"),
        Configuration(defaultValue = "配置"),
        ServerURL(defaultValue = "服务器 URL"),
        ServerSetupInstruction(defaultValue = "确保服务器正在运行。如果本地托管，服务器 URL 应包含正确的端口号。如果不是本地托管，则不需要端口。"),
        SecurityToken(defaultValue = "安全令牌"),
        ServerIsReachable(defaultValue = "服务器存在且可访问！"),
        TestServerAvailability(defaultValue = "测试服务器可用性"),
        UseThisConnection(defaultValue = "使用此连接"),
        ClientToServer(defaultValue = "客户端到服务器"),
        ClientToServerDesc(defaultValue = "客户端更改会发送到服务器，但客户端不会更新服务器的更改。"),
        ServerToClient(defaultValue = "服务器到客户端"),
        ServerToClientDesc(defaultValue = "服务器更改会发送到客户端，但服务器不会更新客户端的更改。"),
        TwoWaySync(defaultValue = "双向同步"),
        TwoWaySyncDesc(defaultValue = "更改双向传输：客户端更新服务器，服务器更新客户端。"),
        ImportLabel(defaultValue = "导入"),
        ImportLabelDesc(defaultValue = "您已连接到同步服务器。要从远程数据库加载现有数据，请使用服务器同步，而不是手动导入。外部导入会导致数据重复，即使数据已存在于远程数据库中。"),
        ExportLabel(defaultValue = "导出"),
        ExportLabelDesc(defaultValue = "导出后，所有与远程数据库关联的数据将被移除，使导出的数据可在不同客户端之间迁移。"),
        ImportUsingJsonFile(defaultValue = "使用 JSON 文件导入"),
        ImportUsingJsonFileDesc(defaultValue = "根据 Linkora 方案从外部 JSON 文件导入数据。"),
        ImportDataFromHtmlFile(defaultValue = "从 HTML 文件导入数据"),
        ImportDataFromHtmlFileDesc(defaultValue = "从符合标准书签导入/导出格式的外部 HTML 文件导入数据。"),
        ExportDataAsJson(defaultValue = "导出数据为 JSON"),
        ExportDataAsJsonDesc(defaultValue = "将所有数据导出为 JSON 文件"),
        ExportDataAsHtml(defaultValue = "导出数据为 HTML"),
        ExportDataAsHtmlDesc(defaultValue = "将所有数据（不包括面板）导出为 HTML 文件"),
        Sync(defaultValue = "同步"),
        ConnectToALinkoraServer(defaultValue = "连接到 Linkora 服务器"),
        ConnectToALinkoraServerDesc(defaultValue = "通过连接到 Linkora 服务器，您可以同步数据，并在任何设备上使用 Linkora 应用访问它。"),
        DeleteEntireDataPermanently(defaultValue = "永久删除所有数据"),
        DeleteEntireDataPermanentlyDesc(defaultValue = "永久删除所有链接、文件夹、面板和本地化字符串。"),
        DeletedEntireDataPermanently(defaultValue = "所有数据已永久删除。"),
        ClearImageCache(defaultValue = "清除图片缓存"),
        ClearImageCacheDesc(defaultValue = "默认情况下，图片会被缓存。更改用户代理可能会影响显示效果。清除缓存以解决问题。"),
        RefreshAllLinksTitlesAndImages(defaultValue = "刷新所有链接的标题和图片"),
        RefreshAllLinksTitlesAndImagesDesc(defaultValue = "手动输入的标题将被检测到的标题替换。"),
        RefreshingLinks(defaultValue = "正在刷新链接…"),
        RefreshingLinksAndroidDesc(defaultValue = "关闭 Linkora 不会中断链接刷新，但新添加的链接可能不会被处理。"),
        RefreshingLinksDesktopDesc(defaultValue = "关闭 Linkora 将取消链接刷新。"),
        InitialScreenOnLaunch(defaultValue = "启动时的初始屏幕"),
        InitialScreenOnLaunchDesc(defaultValue = "此选项的更改将反映在 Linkora 启动时打开的初始屏幕导航中。"),
        Confirm(defaultValue = "确认"),
        SelectTheInitialScreen(defaultValue = "选择启动时的初始屏幕"),
        ShowBorderAroundLinks(defaultValue = "在链接周围显示边框"),
        ShowTitle(defaultValue = "显示标题"),
        ShowBottomFadedEdge(defaultValue = "显示底部渐变边缘"),
        ShowVideoTagOnUIIfApplicable(defaultValue = "在 UI 上显示视频标签（如果适用）"),
        LinkLayoutSettings(defaultValue = "链接布局设置"),
        ChooseTheLayoutYouLikeBest(defaultValue = "选择您喜欢的布局"),
        FeedPreview(defaultValue = "信息流预览"),
        RegularListView(defaultValue = "常规列表视图"),
        TitleOnlyListView(defaultValue = "仅标题列表视图"),
        GridView(defaultValue = "网格视图"),
        StaggeredView(defaultValue = "交错视图"),
        FollowSystemTheme(defaultValue = "跟随系统主题"),
        UseDynamicTheming(defaultValue = "使用动态主题"),
        UseDynamicThemingDesc(defaultValue = "根据您的壁纸更改应用内的颜色主题。"),
        UseAmoledTheme(defaultValue = "使用 AMOLED 主题"),
        RetrieveLanguageInfoFromServer(defaultValue = "从服务器检索语言信息"),
        SelectACollection(defaultValue = "选择一个集合"),
        SelectAPanel(defaultValue = "选择一个面板"),
        FolderHasBeenCreatedSuccessful(defaultValue = "文件夹 ${LinkoraPlaceHolder.First.value} 已成功创建。"),
        RemoteExecutionFailed(defaultValue = "远程执行失败："),
        SavedAvailableLanguagesInfoLocally(defaultValue = "已本地保存可用语言信息。"),
        DeletedTheStringsPack(defaultValue = "已删除 ${LinkoraPlaceHolder.First.value} 语言包。"),
        DownloadedLanguageStrings(defaultValue = "已下载 ${LinkoraPlaceHolder.First.value} 语言字符串。"),
        Linkora(defaultValue = "Linkora"),
        LinkoraIsConnectedToAServer(defaultValue = "Linkora 已连接到服务器；同步基于 ${LinkoraPlaceHolder.First.value}。"),
        CopiedLinkToClipboard(defaultValue = "已复制链接到剪贴板。"),
        FetchingAvailableLanguages(defaultValue = "正在获取可用语言。"),
        DownloadingStrings(defaultValue = "正在下载 ${LinkoraPlaceHolder.First.value} 语言字符串。"),
        CopiedTitleToTheClipboard(defaultValue = "已复制标题到剪贴板。"),
        CopiedNoteToTheClipboard(defaultValue = "已复制备注到剪贴板。"),
        ViewNote(defaultValue = "查看备注"),
        Rename(defaultValue = "重命名"),
        RefreshImageAndTitle(defaultValue = "刷新图片和标题"),
        Refresh(defaultValue = "刷新"),
        UnArchive(defaultValue = "取消归档"),
        UnArchived(defaultValue = "已取消归档，并保存到默认的“已保存链接”集合。"),
        DeleteTheNote(defaultValue = "删除备注"),
        MoveToRootFolders(defaultValue = "移动到根文件夹"),
        DeleteTheLink(defaultValue = "删除链接"),
        DeletedTheLink(defaultValue = "已删除链接。"),
        CopyFolder(defaultValue = "复制文件夹"),
        MoveToOtherFolder(defaultValue = "移动到其他文件夹"),
        CopyLink(defaultValue = "复制链接"),
        MoveLink(defaultValue = "移动链接"),
        DeleteTheFolder(defaultValue = "删除文件夹"),
        DeletedTheFolder(defaultValue = "文件夹 ${LinkoraPlaceHolder.First.value}，所有内部文件夹及相关链接已成功删除。"),
        DeletedTheNoteOfAFolder(defaultValue = "已成功删除 ${LinkoraPlaceHolder.First.value} 文件夹的备注。"),
        DeletedTheNoteOfALink(defaultValue = "已成功删除备注。"),
        FolderDeletionLabel(defaultValue = "删除此文件夹也会删除其所有子文件夹。"),
        AreYouSureDeleteSelectedLinks(defaultValue = "确定要删除所有选定的链接吗？"),
        AreYouSureDeleteLink(defaultValue = "确定要删除该链接吗？"),
        AreYouSureDeleteSelectedFolders(defaultValue = "确定要删除所有选定的文件夹吗？"),
        AreYouSureDeleteFolder(defaultValue = "确定要删除该文件夹吗？"),
        AreYouSureDeleteSelectedItems(defaultValue = "确定要删除所有选定的项目吗？"),
        AreYouSureDeleteEverything(defaultValue = "确定要删除所有文件夹、链接、面板和本地化字符串吗？"),
        SavedNote(defaultValue = "已保存备注。"),
        NoNoteAdded(defaultValue = "您尚未为此添加备注。"),
        Delete(defaultValue = "删除"),
        ArchivedTheFolder(defaultValue = "文件夹 ${LinkoraPlaceHolder.First.value} 已归档。"),
        UnArchivedTheFolder(defaultValue = "文件夹 ${LinkoraPlaceHolder.First.value} 已取消归档。"),
        ArchivedTheLink(defaultValue = "链接已归档。"),
        ChangeBothNameAndNote(defaultValue = "更改名称和备注"),
        ChangeNoteOnly(defaultValue = "仅更改备注"),
        RenameFolder(defaultValue = "重命名文件夹 ${LinkoraPlaceHolder.First.value}："),
        ChangeLinkData(defaultValue = "更改链接数据："),
        NewName(defaultValue = "新名称"),
        NewTitle(defaultValue = "新标题"),
        NewNote(defaultValue = "新备注"),
        UpdatedTheNote(defaultValue = "备注已成功更新。"),
        UpdatedTheName(defaultValue = "名称已成功更新。"),
        UpdatedTheTitle(defaultValue = "标题已成功更新。"),
        UpdatedTheFolderData(defaultValue = "文件夹数据已成功更新。"),
        InvalidLink(defaultValue = "提供的链接无效，请检查并重试。"),
        SavedTheLink(defaultValue = "链接已成功保存。"),
        DeletionInProgress(defaultValue = "正在删除..."),
        RemoveALinkFromImpLink(defaultValue = "从重要链接中移除"),
        MarkALinkAsImpLink(defaultValue = "标记链接为重要"),
        NewestToOldest(defaultValue = "最新到最旧"),
        OldestToNewest(defaultValue = "最旧到最新"),
        AToZSequence(defaultValue = "A 到 Z 顺序"),
        ZToASequence(defaultValue = "Z 到 A 顺序"),
        SortFoldersBy(defaultValue = "按以下方式排序文件夹"),
        SortHistoryLinksBy(defaultValue = "按以下方式排序历史链接"),
        SortBy(defaultValue = "排序依据"),
        SortSavedLinksBy(defaultValue = "按以下方式排序已保存链接"),
        SortImportantLinksBy(defaultValue = "按以下方式排序重要链接"),
        SortBasedOn(defaultValue = "排序依据"),
        SearchTitlesToFindLinksAndFolders(defaultValue = "搜索标题或备注以查找链接和文件夹"),
        RegularFolder(defaultValue = "普通文件夹"),
        ArchiveFolder(defaultValue = "归档文件夹"),
        GoodMorning(defaultValue = "早上好"),
        GoodAfternoon(defaultValue = "下午好"),
        GoodEvening(defaultValue = "晚上好"),
        HeyHi(defaultValue = "嗨👋"),
        Default(defaultValue = "默认"),
        SelectedPanel(defaultValue = "选定的面板"),
        AddANewPanel(defaultValue = "添加新面板"),
        Panels(defaultValue = "面板"),
        FoldersInThisPanel(defaultValue = "此面板中的文件夹"),
        FoldersThatCanBeAddedToThisPanel(defaultValue = "可以添加到此面板的文件夹"),
        PanelName(defaultValue = "面板名称"),
        PermanentlyDeleteThePanel(defaultValue = "永久删除面板"),
        OnceDeletedThisPanelCannotBeRestored(defaultValue = "删除后，此面板无法恢复。"),
        AreYouSureWantToDeleteThePanel(defaultValue = "确定要删除名为 ${LinkoraPlaceHolder.First.value} 的面板吗？"),
        NewNameForPanel(defaultValue = "面板的新名称"),
        ChangePanelName(defaultValue = "更改面板名称"),
        EditPanelName(defaultValue = "编辑 ${LinkoraPlaceHolder.First.value} 面板名称"),
        RedirectToLatestReleasePage(defaultValue = "跳转到最新发布页面"),
        NewUpdateIsAvailable(defaultValue = "Linkora 变得更好啦！新更新可用。"),
        CurrentVersion(defaultValue = "您正在使用的版本"),
        LatestVersionAvailableDesc(defaultValue = "新版本 ${LinkoraPlaceHolder.First.value} 已发布。"),
        TrackRecentChangesAndUpdatesToLinkora(defaultValue = "跟踪 Linkora 的最新更改和更新。"),
        Changelog(defaultValue = "更新日志"),
        OpenAGithubIssue(defaultValue = "在 GitHub 上提交问题"),
        HaveASuggestionCreateAnIssueOnGithubToImproveLinkora(defaultValue = "有建议吗？在 GitHub 上提交问题以改进 Linkora。"),
        GithubDesc(defaultValue = "Linkora 应用、同步服务器和本地化服务器是公开且开源的——欢迎探索代码。"),
        Github(defaultValue = "Github"),
        Discord(defaultValue = "Discord"),
        Twitter(defaultValue = "Twitter"),
        Development(defaultValue = "开发"),
        Socials(defaultValue = "社交"),
        YouAreUsingLatestVersionOfLinkora(defaultValue = "您正在使用最新版本的 Linkora。"),
        CheckForLatestVersion(defaultValue = "检查最新版本"),
        RetrievingLatestInformation(defaultValue = "正在检索最新信息，这可能需要一些时间。"),
        LinkoraOpenSourceAcknowledgement(defaultValue = "没有以下开源软件和库，Linkora 将无法实现。"),
        UserAgent(defaultValue = "用户代理"),
        UserAgentDesc(defaultValue = "从网页元标签中检测图像和标题。检测到的数据可能因使用的代理字符串而异。"),
        LocalizationServerDesc(defaultValue = "Linkora 的本地化服务器允许您在不更新应用的情况下更新字符串。默认情况下，它使用 Linkora 的服务器。\n\n如果需要，您可以切换到自己的服务器。更改将反映在 Linkora 的语言或字符串更新的网络请求中。\n\n只有在您确定自己在做什么时才更改此设置。"),
        LocalizationServer(defaultValue = "本地化服务器"),
        PreparingToExportYourData(defaultValue = "正在准备导出您的数据..."),
        CollectingLinksForExport(defaultValue = "正在收集链接以导出..."),
        CollectingFoldersForExport(defaultValue = "正在收集文件夹以导出..."),
        CollectingPanelsForExport(defaultValue = "正在收集面板以导出..."),
        CollectingPanelFoldersForExport(defaultValue = "正在收集面板文件夹以导出..."),
        SerializingCollectedDataForExport(defaultValue = "正在序列化收集的数据以导出..."),
        ImportExportScreenTopAppBarDesc(defaultValue = "请留在此页面！如果看起来卡住了，请不要惊慌。"),
        ExportedSuccessfully(defaultValue = "导出成功"),
        StoragePermissionIsRequired(defaultValue = "需要存储权限来存储或导出文件。请授予权限以继续。"),
        NotificationPermissionIsRequired(defaultValue = "启用通知权限以查看链接刷新的进度。"),
        PermissionGranted(defaultValue = "权限已授予。请重试操作以继续导入/导出。"),
        LinkRefreshedSuccessfully(defaultValue = "链接数据已成功刷新。"),
        Share(defaultValue = "分享"),
        ForceOpenInABrowser(defaultValue = "在浏览器中打开"),
        WorkManagerDesc(defaultValue = "Work Manager 正在安排链接刷新任务。它将很快继续。\n您可以关闭应用；此任务将在后台继续。"),
        NoOfLinksRefreshed(defaultValue = "${LinkoraPlaceHolder.First.value} / ${LinkoraPlaceHolder.Second.value} 个链接已刷新。"),
        TopDecoratorSetting(defaultValue = "使用 Linkora 的顶部装饰器"),
        TopDecoratorSettingDesc(defaultValue = "禁用时，将使用默认装饰器。更改将在下次启动时应用。"),
        ThisFolderHasNoSubfolders(defaultValue = "此文件夹不包含任何子文件夹。"),
        PanelCreatedSuccessfully(defaultValue = "面板创建成功，名称为：${LinkoraPlaceHolder.First.value}"),
        DeletedPanelSuccessfully(defaultValue = "面板删除成功。"),
        UpdatedThePanelNameSuccessfully(defaultValue = "面板名称已更新为：${LinkoraPlaceHolder.First.value}。"),
        ImportingDataFromTheSever(defaultValue = "从远程服务器导入数据"),
        ImportingDataFromTheSeverDesc(defaultValue = "如果取消导入，部分数据可能仍会保存，并且服务器连接将被移除。"),
        SuccessfullyConnectedToTheServer(defaultValue = "成功连接到服务器。"),
        ConnectionToServerFailed(defaultValue = "无法连接到服务器。请确保服务器可访问。"),
        UpdatingChangesOnRemoteServer(defaultValue = "正在更新远程服务器上的更改"),
        LOLCATplAck(defaultValue = "Android 平板/桌面平台的菜单底部表和链接对话框灵感来自并基于 LOLCATpl 创建的模型。"),
        MondsternAck(defaultValue = "Linkora 应用图标由 mondstern 绘制。"),
        AckEndingText(defaultValue = "当然，这些使用的底层库也会影响 Linkora 的行为。"),
        LOLCATplOnDiscord(defaultValue = "LOLCATpl 在 Discord 上"),
        MondsternOnDiscord(defaultValue = "mondstern 在 Pixelfed 上"),
        NoFoldersOrLinksFound(defaultValue = "未找到文件夹或链接。请添加一些文件夹或链接以开始！"),
        FoldersExistsButNotLinks(defaultValue = "您有文件夹，但还没有链接。添加一些链接以组织您的内容。"),
        NoFoldersFound(defaultValue = "未找到文件夹。添加文件夹以开始。"),
        ExportingDataToJSON(defaultValue = "正在将数据导出为 JSON..."),
        ExportingDataToHTML(defaultValue = "正在将数据导出为 HTML..."),
        ReadingFile(defaultValue = "正在读取文件..."),
        SuccessfullyImportedTheData(defaultValue = "数据导入成功。"),
        SelectAValidFile(defaultValue = "选择一个有效的 ${LinkoraPlaceHolder.First.value} 文件"),
        FileTypeNotSupportedOnDesktopImport(defaultValue = "${LinkoraPlaceHolder.First.value} 文件不支持导入，请选择有效的 ${LinkoraPlaceHolder.Second.value} 文件。"),
        NoFoldersInThePanel(defaultValue = "此面板中没有文件夹。在此面板中添加文件夹以开始。"),
        NoLinksFound(defaultValue = "未找到链接。请添加一些链接以开始！"),
        NoRemoteLangPacks(defaultValue = "未找到远程语言包。请从服务器加载它们。"),
        StringsLocalizedStatus(defaultValue = "${LinkoraPlaceHolder.First.value}/${LinkoraPlaceHolder.Second.value} 字符串已本地化"),
        EnableNotifications(defaultValue = "启用通知"),
        NotificationPermissionRequired(defaultValue = "需要通知权限"),
        NotificationPermissionDesc(defaultValue = "Linkora 需要通知权限以显示数据同步的进度，包括链接刷新。"),
        NoPanelsFound(defaultValue = "没有可用的面板。创建面板并添加相应的文件夹以按项目、研究、任务、事件或任何其他类别进行组织。"),
        SearchInLinkora(defaultValue = "搜索 Linkora：浏览所有保存的链接和文件夹。"),
        NoSearchResults(defaultValue = "没有匹配您的搜索。请记住，您可以按标题和备注进行搜索。再试一次！"),
        NoHistoryFound(defaultValue = "未找到历史记录。您的历史记录是干净的！"),
        StartingImportingProcess(defaultValue = "正在从 JSON 文件导入数据：${LinkoraPlaceHolder.First.value}"),
        DataSynchronizationCompletedSuccessfully(defaultValue = "数据同步成功完成。"),
        InitiateManualSync(defaultValue = "启动手动同步"),
        InitiateManualSyncDesc(defaultValue = "待处理的队列项将被强制推送，而未同步的服务器项将被拉取。"),
        InitiateManualSyncDescAlt(defaultValue = "待处理项将被推送，服务器上的未同步数据将被拉取。"),
        SyncingDataLabel(defaultValue = "正在同步数据..."),
        RemoteDataDeletionFailure(defaultValue = "无法删除远程数据库中的数据。"),
        DeleteEverythingFromRemoteDatabaseLabel(defaultValue = "同时从远程数据库中删除所有数据"),
        ProvideAValidFileLocation(defaultValue = "提供一个有效的文件位置"),
        ImportMethodLabel(defaultValue = "导入方法："),
        FileLocationLabel(defaultValue = "文件位置"),
        FilePickerLabel(defaultValue = "文件选择器"),
        SkipSavingExistingLinksLabel(defaultValue = "跳过保存现有链接"),
        SkipSavingExistingLinksDesc(defaultValue = "如果启用，链接已经存在于目标中时，则不会保存该链接。将会抛出一个错误。"),
        Copy(defaultValue = "复制"),
        Open(defaultValue = "打开"),
        AttachTags(defaultValue = "附加标签"),
        CreateANewTag(defaultValue = "创建新标签"),
        TagDeletionConfirmation(defaultValue = "您确定要删除此标签吗？"),
        SearchFoldersToAdd(defaultValue = "添加的搜索文件夹"),
        CouldNotImportCert(defaultValue = "无法导入证书文件"),
        TagName(defaultValue = "标签名称"),
        SelectAnAppIcon(defaultValue = "选择应用程序图标"),
        ChangeAppIcon(defaultValue = "更改应用程序图标"),
        ChangeAppIconDesc(defaultValue = "确认更改后，应用程序将自动关闭以应用这些更改。通知将继续显示默认的Linkora图标和名称。"),
        ChangeInAppNameDesc(defaultValue = "在你的应用抽屉中，应用名称将显示为“天气”而不是“Linkora”。"),
        AppIconCurrentlyInUse(defaultValue = "当前正在使用的应用程序图标"),
        NoTagsFound(defaultValue = "未找到标签"),
        Tags(defaultValue = "标签"),
        AddedCopyToImpLinks(defaultValue = "向重要链接添加副本"),
        NoAttachmentsToTags(defaultValue = "此标签未附加任何链接。"),
        AboutLibraries(defaultValue = "关于 Libraries"),
        Libraries(defaultValue = "Libraries"),
        ShowOnboardingSlides(defaultValue = "显示新手引导"),
        AppIntroSlide3PanelName(defaultValue = "头脑风暴面板"),
        AppIntroSlide3Folder2Name(defaultValue = "参考资料"),
        AppIntroSlide3Folder2_1Name(defaultValue = "炫酷动画"),
        AppIntroSlide3Folder2_1Note(defaultValue = "流畅切换与顺滑效果"),
        AppIntroSlide3Folder3_1Name(defaultValue = "代码片段"),
        AppIntroSlide3Folder3_1Note(defaultValue = "可复用的小技巧"),
        AppIntroSlide3MainLabel(defaultValue = "介绍面板"),
        AppIntroSlide3MainLabelDesc(defaultValue = "将任何文件夹添加到面板，以便从主屏幕快速访问。面板的工作方式类似于标签，但适用于文件夹。您可以将不同的文件夹分组到每个文件夹下，并立即访问它们。\n哦，是的—— Linkora 也支持子文件夹。"),
        AppIntroSlide4Label1(defaultValue = "等等，\n还有更多。"),
        AppIntroSlide4Label1Desc1(defaultValue = "搜索、排序、自动标题和图像检测(如果可用)。"),
        AppIntroSlide4Label1Desc2(defaultValue = "导出或导入为JSON或HTML格式，支持自动备份。"),
        AppIntroSlide4Label1Desc3(defaultValue = "如果需要，可以与您自己的服务器同步。"),
        AppIntroSlide4Label1Desc4(defaultValue = "打开的链接会保存在历史记录中，即使原始链接已被删除。"),
        AppIntroSlide4Label1Desc5(defaultValue = "支持不同的布局设置。"),
        AppIntroSlide4Label1Desc6(defaultValue = "动态 Material 主题(如果您的设备支持)。"),
        AppIntroSlide4Label1Desc7(defaultValue = "已包含适用于安卓设备的 OLED 主题"),
        AppIntroSlide4Label1Desc8(defaultValue = "使用中央服务器进行本地化—无需应用程序更新的语言更新。"),
        AppIntroSlide4Label1Desc9(defaultValue = "无广告，无付费，自由免费"),
        AppIntroSlide4Label1Desc10(defaultValue = "只是一个简单、可靠的书签。"),
        DeletingDuplicatesLabel(defaultValue = "删除重复项..."),
        SelectedLinksCount(defaultValue = "已选择 ${LinkoraPlaceHolder.First.value} 个链接"),
        SelectedFoldersCount(defaultValue = "已选择 ${LinkoraPlaceHolder.First.value} 个文件夹"),
        MultiActionsLabel(defaultValue = "操作"),
        MarkSelectedFoldersAsRoot(defaultValue = "将所选文件夹标记为根目录"),
        NavigateToCollectionsScreen(defaultValue = "前往收藏夹页面"),
        AppIntroSlide4Label2(defaultValue = "开源，本地优先，个人存储"),
        AppIntroSlide4Label2Desc(defaultValue = "Linkora及其相关项目，包括sync-server，在各自的许可下作为自由和开源软件发布。"),
        PreviousPage(defaultValue = "前一页"),
        NextPage(defaultValue = "下一页"),
        Done(defaultValue = "完成"),
        AppIntroSlide2Folder1Name(defaultValue = "灵感 & 想法"),
        AppIntroSlide2Folder2Name(defaultValue = "说明"),
        AppIntroSlide2Folder2Note(defaultValue = "深度文章或解析"),
        AppIntroSlide2MainLabelDesc(defaultValue = "将链接存储在文件夹中，标记它们，标记为重要或存档，或者将它们保存在“保存的链接”中，使其成为您自己的链接。"),
        AppIntroSlide2MainLabel(defaultValue = "文件夹、链接和\n标签。"),
        AppIntroSlide2Folder1Note(defaultValue = "可能以后会加的一些酷设计"),
        AppIntroSlide1SwipeLabel(defaultValue = "轻扫或点击下一页，了解Linkora的功能。"),
        AppIntroSlide1Label(defaultValue = "Linkora保持你的链接的私密性。\n同步和整理—您除非您设置了自己的服务器，否则任何东西都不会离开的设备。\n没有跟踪，没有云。"),
        Update(defaultValue = "更新"),
        SelectACollectionSource(defaultValue = "选择一个收藏来源"),
        SearchForFolders(defaultValue = "搜索文件夹..."),
        UseCustomAppVersionLabel(defaultValue = "使用自定义应用版本标签"),
        UseCustomAppVersionDesc(defaultValue = "在整个应用程序中启用基于字体的自定义版本标签。"),
        DeleteDuplicateLinksFromAllCollections(defaultValue = "删除重复链接"),
        DeleteDuplicateLinksFromAllCollectionsDesc(defaultValue = "从本地存储和通过Linkora的同步服务器连接的数据库中删除所有重复的链接。"),
        DeletedDuplicatedLinksSuccessfully(defaultValue = "成功删除重复链接。"),
        ShowHostAddress(defaultValue = "显示主机地址"),
        ShowNote(defaultValue = "显示注释"),
        ChangeInitialRoute(defaultValue = "更改初始路径"),
        ChangeInitialRouteDesc(defaultValue = "更改初始路径可让您设置应用程序启动时首先打开哪个屏幕。"),
        Snapshots(defaultValue = "快照"),
        RenameTagName(defaultValue = "重命名标签名称"),
        NewTagName(defaultValue = "新标签名称"),
        ForceShuffleLinks(defaultValue = "强制打乱链接顺序\n"),
        ForceShuffleLinksDesc(defaultValue = "强制打乱链接顺序，覆盖上面的排序类型。这只适用于链接，不适用于文件夹。"),
        Edit(defaultValue = "编辑"),
        AssociatedTags(defaultValue = "关联标签"),
        NoFoldersFoundInArchive(defaultValue = "找不到文件夹"),
        NoArchiveLinksFound(defaultValue = "未找到链接"),
        NavigateAndCopyDesc(defaultValue = "导航到您要复制所选项目的文件夹，点击粘贴按钮将它们复制到那里。"),
        NavigateAndMoveDesc(defaultValue = "导航到您要将所选项目移动到的文件夹，点击“粘贴”按钮将它们移动到那里。"),
        Moving(defaultValue = "正在移动..."),
        Copying(defaultValue = "正在复制..."),
        LinkoraOnTwitter(defaultValue = "Linkora on Twitter"),
        LinkoraOnDiscord(defaultValue = "Linkora on Discord"),
        LinkoraOnGithub(defaultValue = "Linkora on Github"),
        LinkoraIssues(defaultValue = "议题 · LinkoraApp/Linkora"),
        LinokraReleases(defaultValue = "版本发布 · LinkoraApp/Linkora"),
        LinokraReleasesOnGitHub(defaultValue = "版本发布 · LinkoraApp/Linkora（GitHub）"),
        LinkoraIssuesOnGithub(defaultValue = "议题 · LinkoraApp/Linkora（GitHub）"),
        CurrentExportLocation(defaultValue = "当前导出位置"),
        CurrentExportLocationSupportingText(defaultValue = "如果所选目录被删除或移动，导出将静默失败。请确保所选目录始终存在。"),
        ServerCertificateAlreadyImported(defaultValue = "证书已导入。如果不确定其是否与服务器生成的证书匹配，可以导入更新后的证书以替换现有证书。${LinkoraPlaceHolder.First.value}"),
        ImportServerCertificateDescription(defaultValue = "要安全连接，请导入服务器自动生成的 .cer 证书。"),
        ImportedServerCertificate(defaultValue = "已导入：${LinkoraPlaceHolder.First.value}"),
        ProcessingCertificate(defaultValue = "处理证书..."),
        ImportServerCertificate(defaultValue = "导入服务器证书"),
        ForceBypassCertificateChecking(defaultValue = "强制绕过证书检查"),
        ForceBypassCertificateCheckingDescription(defaultValue = "绕过证书验证。不建议这样做。如果您有有效的。cer证书，请禁用此选项，改为导入证书。"),
        Translate(defaultValue = "翻译"),
        BuyMeACoffee(defaultValue = "请我喝杯咖啡"),
        UseSnapshots(defaultValue = "使用快照"),
        UseSnapshotsDescription(defaultValue = "链接、文件夹、面板和面板文件夹将以您选择的格式自动导出。"),
        SnapshotsBackupLocationWarning(defaultValue = "如果选定的目录被移动或删除，备份将会自动失败。确保所选目录始终存在"),
        SnapshotsBackupLocation(defaultValue = "当前备份位置"),
        EnableAutoDeleteSnapshots(defaultValue = "启用旧快照的自动删除"),
        EnableAutoDeleteSnapshotsDescription(defaultValue = "启用后，一旦最旧的快照超过配置的限制，应用程序将自动删除它们。"),
        SnapshotsFileLimitWarning(defaultValue = "文件限制为排他性 - 在创建新备份前检查，而非之后。"),
        SnapshotsFileLimit(defaultValue = "如果快照数量超出限制则自动删除："),
        ExportAs(defaultValue = "导出为"),
        SnapshotsExportDescriptionDesktop(defaultValue = "对链接、文件夹、面板或面板文件夹的每个创建、更新或删除操作都会触发导出。进度显示在侧面导航栏中。"),
        SnapshotsExportDescriptionAndroid(defaultValue = "每当您添加、编辑或删除链接、文件夹、面板或面板文件夹时，Linkora会在后台自动导出。"),
        BackupsWorkOnlyWithDirectory(defaultValue = "只有先选择一个目录，备份才会起作用。"),
        ExportRequiresDirectory(defaultValue = "您需要在导出前选择一个目录。"),
        ArchivedSuccessfully(defaultValue = "归档成功!"),
        DeletedSuccessfully(defaultValue = "删除成功!"),
        ServerCertificateSavedSuccessfully(defaultValue = "服务器证书已成功保存。"),
        Both(defaultValue = "Both"),
    }
}